export interface Turn {
  turnNumber: number;
  timestamp: string;
  speaker: 'Agent AI' | 'Customer';
  text: string;
  confidence: number; // 0-1
  critical: boolean;
  keywordMatchScore: number; //0-1
  expectedIntent: 'greeting' | 'verify_identity' | 'mini_miranda' | 'consent' | 'amount' | 'promise_to_pay' | 'wrapup';
  ruleTriggered: string[];
}

export interface CallMeta {
  callId: string;
  customerName: string;
  startedAt: string;
  timezone: string;
}

export const callMeta: CallMeta = {
  callId: 'CALL-001',
  customerName: 'Juan Pérez',
  startedAt: '14:32',
  timezone: 'CDMX',
};

export const turns: Turn[] = [
  {
    turnNumber: 1,
    timestamp: '00:01',
    speaker: 'Agent AI',
    text: 'Buenas tardes, habla su asistente virtual de cobranza.',
    confidence: 0.95,
    critical: false,
    keywordMatchScore: 0.9,
    expectedIntent: 'greeting',
    ruleTriggered: [],
  },
  {
    turnNumber: 2,
    timestamp: '00:04',
    speaker: 'Customer',
    text: 'Hola, ¿quién llama?',
    confidence: 0.9,
    critical: false,
    keywordMatchScore: 0.8,
    expectedIntent: 'greeting',
    ruleTriggered: [],
  },
  {
    turnNumber: 3,
    timestamp: '00:07',
    speaker: 'Agent AI',
    text: 'Para continuar necesito verificar su identidad.',
    confidence: 0.92,
    critical: false,
    keywordMatchScore: 0.85,
    expectedIntent: 'verify_identity',
    ruleTriggered: [],
  },
  {
    turnNumber: 4,
    timestamp: '00:11',
    speaker: 'Customer',
    text: 'Sí, soy yo.',
    confidence: 0.88,
    critical: false,
    keywordMatchScore: 0.7,
    expectedIntent: 'verify_identity',
    ruleTriggered: [],
  },
  {
    turnNumber: 5,
    timestamp: '00:15',
    speaker: 'Agent AI',
    text: 'Este es un intento de cobrar una deuda.',
    confidence: 0.85,
    critical: true,
    keywordMatchScore: 0.3,
    expectedIntent: 'mini_miranda',
    ruleTriggered: ['missing_disclosure'],
  },
  {
    turnNumber: 6,
    timestamp: '00:19',
    speaker: 'Customer',
    text: 'Ah ok...',
    confidence: 0.8,
    critical: false,
    keywordMatchScore: 0.4,
    expectedIntent: 'mini_miranda',
    ruleTriggered: [],
  },
  {
    turnNumber: 7,
    timestamp: '00:23',
    speaker: 'Agent AI',
    text: '¿Autoriza que la llamada sea grabada?',
    confidence: 0.78,
    critical: true,
    keywordMatchScore: 0.4,
    expectedIntent: 'consent',
    ruleTriggered: [],
  },
  {
    turnNumber: 8,
    timestamp: '00:27',
    speaker: 'Customer',
    text: 'Pues supongo que sí, no importa.',
    confidence: 0.7,
    critical: true,
    keywordMatchScore: 0.3,
    expectedIntent: 'consent',
    ruleTriggered: ['missing_consent'],
  },
  {
    turnNumber: 9,
    timestamp: '00:32',
    speaker: 'Agent AI',
    text: 'Le informo que debe 500 pesos.',
    confidence: 0.9,
    critical: true,
    keywordMatchScore: 0.9,
    expectedIntent: 'amount',
    ruleTriggered: [],
  },
  {
    turnNumber: 10,
    timestamp: '00:36',
    speaker: 'Customer',
    text: '¿Cuándo lo tengo que pagar?',
    confidence: 0.93,
    critical: false,
    keywordMatchScore: 0.8,
    expectedIntent: 'amount',
    ruleTriggered: [],
  },
  {
    turnNumber: 11,
    timestamp: '00:41',
    speaker: 'Agent AI',
    text: 'Puede pagarlo hoy mismo.',
    confidence: 0.88,
    critical: false,
    keywordMatchScore: 0.7,
    expectedIntent: 'promise_to_pay',
    ruleTriggered: [],
  },
  {
    turnNumber: 12,
    timestamp: '00:45',
    speaker: 'Customer',
    text: 'No sé si pueda.',
    confidence: 0.85,
    critical: false,
    keywordMatchScore: 0.6,
    expectedIntent: 'promise_to_pay',
    ruleTriggered: [],
  },
  {
    turnNumber: 13,
    timestamp: '00:49',
    speaker: 'Agent AI',
    text: 'La llamada es un poco tarde, ¿le parece continuar?',
    confidence: 0.82,
    critical: false,
    keywordMatchScore: 0.5,
    expectedIntent: 'wrapup',
    ruleTriggered: ['late_call'],
  },
  {
    turnNumber: 14,
    timestamp: '00:53',
    speaker: 'Customer',
    text: 'Sí, está bien.',
    confidence: 0.87,
    critical: false,
    keywordMatchScore: 0.8,
    expectedIntent: 'wrapup',
    ruleTriggered: [],
  },
  {
    turnNumber: 15,
    timestamp: '00:57',
    speaker: 'Agent AI',
    text: '¿Podemos acordar un pago para mañana?',
    confidence: 0.9,
    critical: false,
    keywordMatchScore: 0.85,
    expectedIntent: 'promise_to_pay',
    ruleTriggered: [],
  },
  {
    turnNumber: 16,
    timestamp: '01:02',
    speaker: 'Customer',
    text: 'Mañana no, quizá la próxima semana.',
    confidence: 0.86,
    critical: false,
    keywordMatchScore: 0.6,
    expectedIntent: 'promise_to_pay',
    ruleTriggered: [],
  },
  {
    turnNumber: 17,
    timestamp: '01:07',
    speaker: 'Agent AI',
    text: 'Entiendo, ¿qué día le conviene?',
    confidence: 0.9,
    critical: false,
    keywordMatchScore: 0.7,
    expectedIntent: 'promise_to_pay',
    ruleTriggered: [],
  },
  {
    turnNumber: 18,
    timestamp: '01:11',
    speaker: 'Customer',
    text: 'El viernes quizá.',
    confidence: 0.9,
    critical: false,
    keywordMatchScore: 0.6,
    expectedIntent: 'promise_to_pay',
    ruleTriggered: [],
  },
  {
    turnNumber: 19,
    timestamp: '01:15',
    speaker: 'Agent AI',
    text: 'Perfecto, agendamos para el viernes.',
    confidence: 0.92,
    critical: false,
    keywordMatchScore: 0.8,
    expectedIntent: 'wrapup',
    ruleTriggered: [],
  },
  {
    turnNumber: 20,
    timestamp: '01:19',
    speaker: 'Customer',
    text: 'Gracias, adiós.',
    confidence: 0.95,
    critical: false,
    keywordMatchScore: 0.9,
    expectedIntent: 'wrapup',
    ruleTriggered: [],
  },
];
