export interface Turn {
  turnNumber: number;
  timestamp: string;
  speaker: 'Agent AI' | 'Customer';
  text: string;
  confidence: number; // 0-1
  critical: boolean;
  keywordMatchScore: number; //0-1
  expectedIntent: 'greeting' | 'verify_identity' | 'mini_miranda' | 'consent' | 'amount' | 'promise_to_pay' | 'wrapup';
  ruleTriggered: string[];
}

export interface CallMeta {
  callId: string;
  customerName: string;
  startedAt: string;
  timezone: string;
}

export const callMeta: CallMeta = {
  callId: 'CALL-001',
  customerName: 'John Perez',
  startedAt: '14:32',
  timezone: 'Mexico City',
};

export const turns: Turn[] = [
  {
    turnNumber: 1,
    timestamp: '00:01',
    speaker: 'Agent AI',
    text: 'Good afternoon, this is your virtual collections assistant speaking.',
    confidence: 0.95,
    critical: false,
    keywordMatchScore: 0.9,
    expectedIntent: 'greeting',
    ruleTriggered: [],
  },
  {
    turnNumber: 2,
    timestamp: '00:04',
    speaker: 'Customer',
    text: "Hello, who's calling?",
    confidence: 0.9,
    critical: false,
    keywordMatchScore: 0.8,
    expectedIntent: 'greeting',
    ruleTriggered: [],
  },
  {
    turnNumber: 3,
    timestamp: '00:07',
    speaker: 'Agent AI',
    text: 'To continue I need to verify your identity.',
    confidence: 0.92,
    critical: false,
    keywordMatchScore: 0.85,
    expectedIntent: 'verify_identity',
    ruleTriggered: [],
  },
  {
    turnNumber: 4,
    timestamp: '00:11',
    speaker: 'Customer',
    text: "Yes, it's me.",
    confidence: 0.88,
    critical: false,
    keywordMatchScore: 0.7,
    expectedIntent: 'verify_identity',
    ruleTriggered: [],
  },
  {
    turnNumber: 5,
    timestamp: '00:15',
    speaker: 'Agent AI',
    text: 'This is an attempt to collect a debt.',
    confidence: 0.85,
    critical: true,
    keywordMatchScore: 0.3,
    expectedIntent: 'mini_miranda',
    ruleTriggered: ['missing_disclosure'],
  },
  {
    turnNumber: 6,
    timestamp: '00:19',
    speaker: 'Customer',
    text: 'Oh okay...',
    confidence: 0.8,
    critical: false,
    keywordMatchScore: 0.4,
    expectedIntent: 'mini_miranda',
    ruleTriggered: [],
  },
  {
    turnNumber: 7,
    timestamp: '00:23',
    speaker: 'Agent AI',
    text: 'Do you authorize this call to be recorded?',
    confidence: 0.78,
    critical: true,
    keywordMatchScore: 0.4,
    expectedIntent: 'consent',
    ruleTriggered: [],
  },
  {
    turnNumber: 8,
    timestamp: '00:27',
    speaker: 'Customer',
    text: "I guess so, it doesn't matter.",
    confidence: 0.7,
    critical: true,
    keywordMatchScore: 0.3,
    expectedIntent: 'consent',
    ruleTriggered: ['missing_consent'],
  },
  {
    turnNumber: 9,
    timestamp: '00:32',
    speaker: 'Agent AI',
    text: 'I am informing you that you owe 500 pesos.',
    confidence: 0.9,
    critical: true,
    keywordMatchScore: 0.9,
    expectedIntent: 'amount',
    ruleTriggered: [],
  },
  {
    turnNumber: 10,
    timestamp: '00:36',
    speaker: 'Customer',
    text: 'When do I have to pay it?',
    confidence: 0.93,
    critical: false,
    keywordMatchScore: 0.8,
    expectedIntent: 'amount',
    ruleTriggered: [],
  },
  {
    turnNumber: 11,
    timestamp: '00:41',
    speaker: 'Agent AI',
    text: 'You can pay it today.',
    confidence: 0.88,
    critical: false,
    keywordMatchScore: 0.7,
    expectedIntent: 'promise_to_pay',
    ruleTriggered: [],
  },
  {
    turnNumber: 12,
    timestamp: '00:45',
    speaker: 'Customer',
    text: "I'm not sure I can.",
    confidence: 0.85,
    critical: false,
    keywordMatchScore: 0.6,
    expectedIntent: 'promise_to_pay',
    ruleTriggered: [],
  },
  {
    turnNumber: 13,
    timestamp: '00:49',
    speaker: 'Agent AI',
    text: 'This call is a bit late, is it okay to continue?',
    confidence: 0.82,
    critical: false,
    keywordMatchScore: 0.5,
    expectedIntent: 'wrapup',
    ruleTriggered: ['late_call'],
  },
  {
    turnNumber: 14,
    timestamp: '00:53',
    speaker: 'Customer',
    text: "Yes, that's fine.",
    confidence: 0.87,
    critical: false,
    keywordMatchScore: 0.8,
    expectedIntent: 'wrapup',
    ruleTriggered: [],
  },
  {
    turnNumber: 15,
    timestamp: '00:57',
    speaker: 'Agent AI',
    text: 'Can we arrange a payment for tomorrow?',
    confidence: 0.9,
    critical: false,
    keywordMatchScore: 0.85,
    expectedIntent: 'promise_to_pay',
    ruleTriggered: [],
  },
  {
    turnNumber: 16,
    timestamp: '01:02',
    speaker: 'Customer',
    text: 'Not tomorrow, maybe next week.',
    confidence: 0.86,
    critical: false,
    keywordMatchScore: 0.6,
    expectedIntent: 'promise_to_pay',
    ruleTriggered: [],
  },
  {
    turnNumber: 17,
    timestamp: '01:07',
    speaker: 'Agent AI',
    text: 'I understand, what day works for you?',
    confidence: 0.9,
    critical: false,
    keywordMatchScore: 0.7,
    expectedIntent: 'promise_to_pay',
    ruleTriggered: [],
  },
  {
    turnNumber: 18,
    timestamp: '01:11',
    speaker: 'Customer',
    text: 'Maybe Friday.',
    confidence: 0.9,
    critical: false,
    keywordMatchScore: 0.6,
    expectedIntent: 'promise_to_pay',
    ruleTriggered: [],
  },
  {
    turnNumber: 19,
    timestamp: '01:15',
    speaker: 'Agent AI',
    text: "Perfect, we'll schedule it for Friday.",
    confidence: 0.92,
    critical: false,
    keywordMatchScore: 0.8,
    expectedIntent: 'wrapup',
    ruleTriggered: [],
  },
  {
    turnNumber: 20,
    timestamp: '01:19',
    speaker: 'Customer',
    text: 'Thank you, goodbye.',
    confidence: 0.95,
    critical: false,
    keywordMatchScore: 0.9,
    expectedIntent: 'wrapup',
    ruleTriggered: [],
  },
];
